/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RP;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author rahma
 */
public class FeedBack extends javax.swing.JFrame {

    /**
     * Creates new form FeedBack
     */
    public FeedBack() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        RUSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        RUProfile1 = new javax.swing.JLabel();
        RVSR1 = new javax.swing.JLabel();
        RVSU1 = new javax.swing.JLabel();
        RUPH1 = new javax.swing.JLabel();
        feedback1 = new javax.swing.JLabel();
        menu1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        RUSearch.setBackground(new java.awt.Color(0, 102, 51));
        RUSearch.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RUSearch.setForeground(new java.awt.Color(255, 255, 255));
        RUSearch.setText("Search");
        RUSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RUSearchMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(153, 0, 153));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Online Resource Sharing System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RUSearch)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RUSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        RUProfile1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RUProfile1.setForeground(new java.awt.Color(255, 255, 255));
        RUProfile1.setText("Profile");
        RUProfile1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RUProfile1MouseClicked(evt);
            }
        });

        RVSR1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RVSR1.setForeground(new java.awt.Color(255, 255, 255));
        RVSR1.setText("Share Resources");
        RVSR1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RVSR1MouseClicked(evt);
            }
        });

        RVSU1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RVSU1.setForeground(new java.awt.Color(255, 255, 255));
        RVSU1.setText("System Usage");
        RVSU1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RVSU1MouseClicked(evt);
            }
        });

        RUPH1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RUPH1.setForeground(new java.awt.Color(255, 255, 255));
        RUPH1.setText("Payment History");
        RUPH1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RUPH1MouseClicked(evt);
            }
        });

        feedback1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        feedback1.setForeground(new java.awt.Color(255, 255, 255));
        feedback1.setText("Feedbacks");
        feedback1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feedback1MouseClicked(evt);
            }
        });

        menu1.setBackground(new java.awt.Color(0, 102, 51));
        menu1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        menu1.setForeground(new java.awt.Color(255, 255, 255));
        menu1.setText("Return To Menu");
        menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RUPH1)
                    .addComponent(RVSU1)
                    .addComponent(RVSR1)
                    .addComponent(RUProfile1)
                    .addComponent(menu1)
                    .addComponent(feedback1))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(RUProfile1)
                .addGap(26, 26, 26)
                .addComponent(RVSR1)
                .addGap(28, 28, 28)
                .addComponent(RVSU1)
                .addGap(33, 33, 33)
                .addComponent(RUPH1)
                .addGap(33, 33, 33)
                .addComponent(feedback1)
                .addGap(49, 49, 49)
                .addComponent(menu1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Feedbacks: ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RUSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RUSearchMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RUSearchMouseClicked

    private void RUProfile1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RUProfile1MouseClicked
        // TODO add your handling code here:
        RVProfileFrame pf=new RVProfileFrame();
        pf.setVisible(true);
        pf.setLocationRelativeTo(null);
        pf.pack();
        //this.dispose();
    }//GEN-LAST:event_RUProfile1MouseClicked

    private void RVSR1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RVSR1MouseClicked
        // TODO add your handling code here:
        RVShareFrame or=new RVShareFrame();
        or.setVisible(true);
        or.setLocationRelativeTo(null);
        or.pack();
        this.dispose();
    }//GEN-LAST:event_RVSR1MouseClicked

    private void RVSU1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RVSU1MouseClicked
        try {
            // TODO add your handling code here:
            RVSI af=new RVSI();
            af.setVisible(true);
            af.setLocationRelativeTo(null);
            af.pack();
            this.dispose();
        } catch (ParseException ex) {
            Logger.getLogger(FeedBack.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RVSU1MouseClicked

    private void RUPH1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RUPH1MouseClicked
        // TODO add your handling code here:
        PaymentHistoryFrame ph=new PaymentHistoryFrame();
        ph.setVisible(true);
        ph.setLocationRelativeTo(null);
        ph.pack();
        this.dispose();
    }//GEN-LAST:event_RUPH1MouseClicked

    private void feedback1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedback1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_feedback1MouseClicked

    private void menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu1ActionPerformed
        // TODO add your handling code here:
        RVinterface in=new RVinterface();
        in.setVisible(true);
        in.setLocationRelativeTo(null);
        in.pack();
        this.dispose();
    }//GEN-LAST:event_menu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FeedBack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FeedBack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FeedBack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FeedBack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FeedBack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RUPH1;
    private javax.swing.JLabel RUProfile1;
    private javax.swing.JButton RUSearch;
    private javax.swing.JLabel RVSR1;
    private javax.swing.JLabel RVSU1;
    private javax.swing.JLabel feedback1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton menu1;
    // End of variables declaration//GEN-END:variables
}
