/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RP;

import RU.login;
import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import static java.lang.String.format;
import java.net.Socket;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import org.json.JSONObject;

/**
 *
 * @author rahma
 */
public class RVSI extends javax.swing.JFrame {

    /**
     * Creates new form RVSI
     */
    private String uname;
    public RVSI() throws ParseException {
        OutputStreamWriter os = null;
        long hours = 0;
        try {
            initComponents();
           // this.uname = loginRV.uName;
            this.uname = "tourist";
            setResizable(false);
            Socket s = new Socket(login.ip, 10002);
            os = new OutputStreamWriter(s.getOutputStream());
            PrintWriter out = new PrintWriter(os);
            JSONObject ob = new JSONObject();
            ob.put("name", uname);
            ob.put("who", "RP");
            ob.toString();
            out.println(ob);
            os.flush();
            BufferedReader br = new BufferedReader(new InputStreamReader(s.getInputStream()));
            String row = br.readLine();
            System.out.println("DataPaisi");
            System.out.println(row);
            String data = "";
            for(int ch=0; ch<row.length(); ch++){
                if(row.charAt(ch)=='[' || row.charAt(ch)==']'){
                    continue;
                }
                if(row.charAt(ch)==' '){
                    if(ch-1>=0 && row.charAt(ch-1)==',')
                        continue;
                }
                if(row.charAt(ch)==',' && ch+1<row.length() && row.charAt(ch+2)=='{')
                    continue;
                data += row.charAt(ch);
            }
            System.out.println(data);
            List<String> myList = new ArrayList<String>(Arrays.asList(data.split("}")));
            int a=18,b=220,c=500,d=20;
            for(String val : myList){
                val += "}";
                JSONObject ob2 = new JSONObject(val);
                SimpleDateFormat format = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");

		Date d1 = null;
		Date d2 = null;
		try {
			d1 = format.parse(ob2.getString("startTimeDate"));
			d2 = format.parse(ob2.getString("endTimeDate"));

			//in milliseconds
			long diff = d2.getTime() - d1.getTime();
			long diffHours = diff / (60 * 60 * 1000) % 24;
                        hours += diffHours;
			System.out.print(diffHours + " hours, ");

		} catch (Exception e) {
			e.printStackTrace();
		}
                JLabel lbl= new JLabel(ob2.getString("startTimeDate"));
                JLabel lbl2 = new JLabel("Your Resource Were used by " + ob2.getString("User_Name"));
                lbl.setBounds(a, b, c, d);
                b += d;
                b += 5;
                lbl2.setBounds(a,b,c,d);
                lbl.setForeground(Color.red);
                lbl2.setForeground(Color.red);
                lbl.setFont(new Font("Times New Roman", Font.BOLD, 14));
                lbl.setFont(new Font("Times New Roman", Font.BOLD, 11));
                jPanel4.add(lbl);
                jPanel4.add(lbl2);
                b += d;
                b += 20;
                
            }   
            jTextField2.setText(Long.toString(hours));
        } catch (IOException ex) {
            Logger.getLogger(RVSI.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                os.close();
            } catch (IOException ex) {
                Logger.getLogger(RVSI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        RUProfile = new javax.swing.JLabel();
        RVSR = new javax.swing.JLabel();
        RVSU = new javax.swing.JLabel();
        RUPH = new javax.swing.JLabel();
        feedback = new javax.swing.JLabel();
        menu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        RUSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        RUProfile1 = new javax.swing.JLabel();
        RVSR1 = new javax.swing.JLabel();
        RVSU1 = new javax.swing.JLabel();
        RUPH1 = new javax.swing.JLabel();
        feedback1 = new javax.swing.JLabel();
        menu1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        RUProfile.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RUProfile.setForeground(new java.awt.Color(255, 255, 255));
        RUProfile.setText("Profile");
        RUProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RUProfileMouseClicked(evt);
            }
        });

        RVSR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RVSR.setForeground(new java.awt.Color(255, 255, 255));
        RVSR.setText("Share Resources");
        RVSR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RVSRMouseClicked(evt);
            }
        });

        RVSU.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RVSU.setForeground(new java.awt.Color(255, 255, 255));
        RVSU.setText("System Usage");
        RVSU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RVSUMouseClicked(evt);
            }
        });

        RUPH.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RUPH.setForeground(new java.awt.Color(255, 255, 255));
        RUPH.setText("Payment History");
        RUPH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RUPHMouseClicked(evt);
            }
        });

        feedback.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        feedback.setForeground(new java.awt.Color(255, 255, 255));
        feedback.setText("Feedbacks");
        feedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feedbackMouseClicked(evt);
            }
        });

        menu.setBackground(new java.awt.Color(0, 102, 51));
        menu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        menu.setForeground(new java.awt.Color(255, 255, 255));
        menu.setText("Return To Menu");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RUPH)
                    .addComponent(RVSU)
                    .addComponent(RVSR)
                    .addComponent(RUProfile)
                    .addComponent(menu)
                    .addComponent(feedback))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(RUProfile)
                .addGap(26, 26, 26)
                .addComponent(RVSR)
                .addGap(28, 28, 28)
                .addComponent(RVSU)
                .addGap(33, 33, 33)
                .addComponent(RUPH)
                .addGap(33, 33, 33)
                .addComponent(feedback)
                .addGap(133, 133, 133)
                .addComponent(menu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        RUSearch.setBackground(new java.awt.Color(0, 102, 51));
        RUSearch.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RUSearch.setForeground(new java.awt.Color(255, 255, 255));
        RUSearch.setText("Search");
        RUSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RUSearchMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(153, 0, 153));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Online Resource Sharing System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RUSearch)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RUSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        RUProfile1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RUProfile1.setForeground(new java.awt.Color(255, 255, 255));
        RUProfile1.setText("Profile");
        RUProfile1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RUProfile1MouseClicked(evt);
            }
        });

        RVSR1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RVSR1.setForeground(new java.awt.Color(255, 255, 255));
        RVSR1.setText("Share Resources");
        RVSR1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RVSR1MouseClicked(evt);
            }
        });

        RVSU1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RVSU1.setForeground(new java.awt.Color(255, 255, 255));
        RVSU1.setText("System Usage");
        RVSU1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RVSU1MouseClicked(evt);
            }
        });

        RUPH1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RUPH1.setForeground(new java.awt.Color(255, 255, 255));
        RUPH1.setText("Payment History");
        RUPH1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RUPH1MouseClicked(evt);
            }
        });

        feedback1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        feedback1.setForeground(new java.awt.Color(255, 255, 255));
        feedback1.setText("Feedbacks");
        feedback1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feedback1MouseClicked(evt);
            }
        });

        menu1.setBackground(new java.awt.Color(0, 102, 51));
        menu1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        menu1.setForeground(new java.awt.Color(255, 255, 255));
        menu1.setText("Return To Menu");
        menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RUPH1)
                    .addComponent(RVSU1)
                    .addComponent(RVSR1)
                    .addComponent(RUProfile1)
                    .addComponent(menu1)
                    .addComponent(feedback1))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(RUProfile1)
                .addGap(26, 26, 26)
                .addComponent(RVSR1)
                .addGap(28, 28, 28)
                .addComponent(RVSU1)
                .addGap(33, 33, 33)
                .addComponent(RUPH1)
                .addGap(33, 33, 33)
                .addComponent(feedback1)
                .addGap(49, 49, 49)
                .addComponent(menu1)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total Hours: ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usage Information: ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RUProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RUProfileMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_RUProfileMouseClicked

    private void RVSRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RVSRMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_RVSRMouseClicked

    private void RVSUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RVSUMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_RVSUMouseClicked

    private void RUPHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RUPHMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RUPHMouseClicked

    private void feedbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedbackMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_feedbackMouseClicked

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuActionPerformed

    private void RUSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RUSearchMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RUSearchMouseClicked

    private void RUProfile1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RUProfile1MouseClicked
        // TODO add your handling code here:
        RVProfileFrame pf=new RVProfileFrame();
        pf.setVisible(true);
        pf.setLocationRelativeTo(null);
        pf.pack();
        this.dispose();
    }//GEN-LAST:event_RUProfile1MouseClicked

    private void RVSR1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RVSR1MouseClicked
        // TODO add your handling code here:
        RVShareFrame or=new RVShareFrame();
        or.setVisible(true);
        or.setLocationRelativeTo(null);
        or.pack();
        this.dispose();
    }//GEN-LAST:event_RVSR1MouseClicked

    private void RVSU1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RVSU1MouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_RVSU1MouseClicked

    private void RUPH1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RUPH1MouseClicked
        // TODO add your handling code here:
         PaymentHistoryFrame ph=new PaymentHistoryFrame();
        ph.setVisible(true);
        ph.setLocationRelativeTo(null);
        ph.pack();
        this.dispose();
    }//GEN-LAST:event_RUPH1MouseClicked

    private void feedback1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedback1MouseClicked
        // TODO add your handling code here:
        FeedBack af=new FeedBack();
        af.setVisible(true);
        af.setLocationRelativeTo(null);
        af.pack();
        this.dispose();
    }//GEN-LAST:event_feedback1MouseClicked

    private void menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu1ActionPerformed
        // TODO add your handling code here:
        RVinterface in=new RVinterface();
        in.setVisible(true);
        in.setLocationRelativeTo(null);
        in.pack();
        this.dispose();
    }//GEN-LAST:event_menu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RVSI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RVSI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RVSI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RVSI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new RVSI().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(RVSI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RUPH;
    private javax.swing.JLabel RUPH1;
    private javax.swing.JLabel RUProfile;
    private javax.swing.JLabel RUProfile1;
    private javax.swing.JButton RUSearch;
    private javax.swing.JLabel RVSR;
    private javax.swing.JLabel RVSR1;
    private javax.swing.JLabel RVSU;
    private javax.swing.JLabel RVSU1;
    private javax.swing.JLabel feedback;
    private javax.swing.JLabel feedback1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton menu;
    private javax.swing.JButton menu1;
    // End of variables declaration//GEN-END:variables
}
